# Generated by Django 5.0.6 on 2024-07-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_student_mphn_no_alter_student_fphn_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mphn_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='fphn_no',
            field=models.IntegerField(),
        ),
    ]
